module.exports = {
    angular: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/fonts',   dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/api',     dest: "angular/api"},
            {expand: true, src: "**", cwd: 'src/l10n',    dest: "angular/l10n"},
            {expand: true, src: "**", cwd: 'src/img',     dest: "angular/img"},
            {expand: true, src: "**", cwd: 'src/js',      dest: "angular/js"},
            {expand: true, src: "**", cwd: 'src/tpl',     dest: "angular/tpl"},
            {expand: true, src: "**", cwd: 'src/conf',     dest: "angular/"},
            {expand: true, src: "**", cwd: 'bower_components/jquery.easy-pie-chart/dist/', dest: 'angular/bower_components/jquery.easy-pie-chart/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/jquery.sparkline/dist/jquery.sparkline.retina.js', dest: 'angular/bower_components/jquery.sparkline/dist/jquery.sparkline.retina.js'},
            {expand: true, src: "**", cwd: 'bower_components/flot/', dest: 'angular/bower_components/flot/'},
            {expand: true, src: "**", cwd: 'bower_components/flot.tooltip/js/', dest: 'angular/bower_components/flot.tooltip/js/'},
            {expand: true, src: "**", cwd: 'bower_components/flot.orderbars/js/', dest: 'angular/bower_components/flot.orderbars/js/'},
            {expand: true, src: "**", cwd: 'bower_components/flot-spline/', dest: 'angular/bower_components/flot-spline/'},
            {expand: true, src: "**", cwd: 'bower_components/bower-jvectormap', dest: 'angular/bower_components/bower-jvectormap/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-daterangepicker', dest: 'angular/bower_components/bootstrap-daterangepicker/'},
            {expand: true, src: "**", cwd: 'bower_components/fullcalendar/dist/', dest: 'angular/bower_components/fullcalendar/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/moment/', dest: 'angular/bower_components/moment/'},
            {expand: true, src: "**", cwd: 'bower_components/nestable/', dest: 'angular/bower_components/nestable/'},
            {expand: true, src: "**", cwd: 'bower_components/footable/dist/', dest: 'angular/bower_components/footable/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/footable/css', dest: 'angular/bower_components/footable/css/'},
            {expand: true, src: "**", cwd: 'bower_components/screenfull/dist/', dest: 'angular/bower_components/screenfull/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/slimscroll/', dest: 'angular/bower_components/slimscroll/'},
            {expand: true, src: "**", cwd: 'bower_components/html5sortable/', dest: 'angular/bower_components/html5sortable/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-slider/', dest: 'angular/bower_components/bootstrap-slider/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-touchspin/dist/', dest: 'angular/bower_components/bootstrap-touchspin/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-filestyle/src/', dest: 'angular/bower_components/bootstrap-filestyle/src/'},
            {expand: true, src: "**", cwd: 'bower_components/chosen/', dest: 'angular/bower_components/chosen/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-wysiwyg/', dest: 'angular/bower_components/bootstrap-wysiwyg/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-chosen/', dest: 'angular/bower_components/bootstrap-chosen/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-wysiwyg/external/', dest: 'angular/bower_components/bootstrap-wysiwyg/external/'},
            {expand: true, src: "**", cwd: 'bower_components/datatables/media/js/', dest: 'angular/bower_components/datatables/media/js/'},
            {expand: true, src: "**", cwd: 'bower_components/plugins/integration/bootstrap/3/', dest: 'angular/bower_components/plugins/integration/bootstrap/3/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-tagsinput/dist/', dest: 'angular/bower_components/bootstrap-tagsinput/dist/'},
            {expand: true, src: "**", cwd: 'bower_components/bootstrap-tagsinput/dist/', dest: 'angular/bower_components/bootstrap-tagsinput/dist/'},
            {expand: true, src: "spin.min.js", cwd: 'bower_components/spin.js/', dest: 'angular/bower_components/spin.js/'},
            {expand: true, src: 'ui-grid.eot', cwd:'bower_components/angular-ui-grid/', dest : 'angular/css/',flatten: true},
            {expand: true, src: 'ui-grid.svg', cwd:'bower_components/angular-ui-grid/', dest : 'angular/css/'},
            {expand: true, src: 'ui-grid.ttf', cwd:'bower_components/angular-ui-grid/', dest : 'angular/css/'},
            {expand: true, src: 'ui-grid.woff',cwd:'bower_components/angular-ui-grid/', dest : 'angular/css/'},
            {expand: true, src: "toastr.min.css", cwd: 'bower_components/toastr/',     dest: "angular/css"},
            // {expand: true, src: "toastr.js", cwd: 'bower_components/toastr/',     dest: "angular/js"},
            {expand: true, src: "**", cwd: 'src/conf',     dest: "angular/"},
            {src: 'src/index.min.html', dest : 'angular/index.html'}
        ]
    }
};
