module.exports = {
  angular:{
    src:[
      'angular/js/app.src.js'
    ],
    dest:'angular/js/app.min.js'
  },
  qstar:{
    src:[
      'qstar/js/app.src.js'
    ],
    dest:'qstar/js/app.min.js'
  },
  truepaas:{
    src:[
      'truepaas/js/app.src.js'
    ],
    dest:'truepaas/js/app.min.js'
  }
}
